// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Get All Metric in html format",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Get Metrics"
                ],
                "summary": "Get All Metric",
                "responses": {
                    "200": {
                        "description": "OK, return metric value",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error, can't write response body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/echoping": {
            "get": {
                "description": "Request echo reply from server",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Ping debug"
                ],
                "summary": "Test handler for service",
                "operationId": "pongHandler",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping/": {
            "get": {
                "description": "Check connection to DB",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "DB Check"
                ],
                "summary": "Check DB",
                "operationId": "checkDB",
                "responses": {
                    "200": {
                        "description": "DB available",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update/": {
            "post": {
                "description": "Update one metric in json by it name and value (in json)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "JSON Metrics"
                ],
                "summary": "Update one metric in json",
                "parameters": [
                    {
                        "description": "JSON, contains Metric ID,type,value",
                        "name": "bodyReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metrics.Metrics"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK, update/add metric value",
                        "schema": {
                            "$ref": "#/definitions/metrics.Metrics"
                        }
                    },
                    "404": {
                        "description": "Not found, can't found metric by ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update/counter/{name}/{value}": {
            "post": {
                "description": "Update Counter metric",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Update Metrics"
                ],
                "summary": "Update Counters",
                "operationId": "updateCounter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metric name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Metric value",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Wrong request, can't parse number",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update/gauge/{name}/{value}": {
            "post": {
                "description": "Update gauge metric",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Update Metrics"
                ],
                "summary": "Update Gauges",
                "operationId": "updateGauge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metric name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Metric value",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Wrong request, can't parse number",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/updates/": {
            "post": {
                "description": "Update metric in json by it name and value (in json)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "JSON Metrics"
                ],
                "summary": "Update metrics in json",
                "parameters": [
                    {
                        "description": "JSON, contains Metric ID,type,value",
                        "name": "bodyReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metrics.Metrics"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK, update/add metric value",
                        "schema": {
                            "$ref": "#/definitions/metrics.Metrics"
                        }
                    },
                    "500": {
                        "description": "Internal error, can't update any metric",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/value/": {
            "post": {
                "description": "Get one metric in json by it name (in json)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "JSON Metrics"
                ],
                "summary": "Get one metric in json",
                "parameters": [
                    {
                        "description": "MetricID",
                        "name": "bodyReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metrics.Metrics"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK, return metric value",
                        "schema": {
                            "$ref": "#/definitions/metrics.Metrics"
                        }
                    },
                    "404": {
                        "description": "Not found, can't found metric by ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{mType}/{mName}": {
            "get": {
                "description": "Get one metric by name",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Get Metrics"
                ],
                "summary": "Get one metric",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metric type",
                        "name": "mType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Metric name",
                        "name": "mName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK, return metric value",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Wrong request, can't parse number",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Metric not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error, can't write response body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "metrics.Metrics": {
            "type": "object",
            "properties": {
                "delta": {
                    "description": "значение метрики в случае передачи counter",
                    "type": "integer"
                },
                "id": {
                    "description": "имя метрики",
                    "type": "string"
                },
                "type": {
                    "description": "параметр, принимающий значение gauge или counter",
                    "type": "string"
                },
                "value": {
                    "description": "значение метрики в случае передачи gauge",
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MetricServer Endpoints",
	Description:      "Service for storing metrics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
